import { type Product } from "@/components/shop/ProductCard";

export const featuredProducts: Product[] = [
  {
    id: "starter",
    name: "스타터 패키지",
    desc: "서버 생활에 필요한 필수 아이템!",
    price: 5500,
    emoji: "⚔️",
    emojiColor: "bg-slate-700/50",
    badge: "HOT",
    category: "package",
  },
  {
    id: "vip-30",
    name: "VIP 등급 [30일]",
    desc: "다양한 혜택이 포함된 VIP 등급",
    price: 9900,
    emoji: "👑",
    emojiColor: "bg-yellow-900/40",
    badge: "HOT",
    category: "membership",
  },
  {
    id: "emerald-1000",
    name: "에메랄드 1,000개",
    desc: "게임 내 재화 에메랄드",
    price: 11000,
    emoji: "💚",
    emojiColor: "bg-green-900/40",
    category: "currency",
  },
  {
    id: "mage-pack",
    name: "마법사 패키지",
    desc: "마법 관련 아이템 모음",
    price: 8800,
    emoji: "🔮",
    emojiColor: "bg-purple-900/40",
    category: "package",
  },
  {
    id: "skyblock-pack",
    name: "스카이블럭 패키지",
    desc: "스카이블럭에 특화된 아이템",
    price: 7700,
    emoji: "🪨",
    emojiColor: "bg-stone-700/50",
    category: "package",
  },
];

export const allProducts: Product[] = [
  {
    id: "diamond-100",
    name: "다이아몬드 100개",
    desc: "최고급 광물 다이아몬드",
    price: 1100,
    emoji: "💎",
    emojiColor: "bg-cyan-900/40",
    category: "currency",
  },
  {
    id: "gold-100",
    name: "골드 100개",
    desc: "금괴 100개 묶음",
    price: 990,
    emoji: "🪙",
    emojiColor: "bg-yellow-800/40",
    category: "currency",
  },
  {
    id: "exp-booster-1h",
    name: "경험치 부스터 [1시간]",
    desc: "1시간 동안 경험치 2배 획득",
    price: 1500,
    emoji: "✨",
    emojiColor: "bg-lime-900/40",
    category: "utility",
    badge: "NEW",
  },
  {
    id: "fly-7",
    name: "비행권 [7일]",
    desc: "7일 동안 자유 비행 가능",
    price: 5500,
    emoji: "🪶",
    emojiColor: "bg-slate-700/40",
    category: "utility",
  },
  {
    id: "home-move",
    name: "홈 이전권",
    desc: "홈 위치를 새롭게 설정",
    price: 3300,
    emoji: "🏠",
    emojiColor: "bg-amber-900/40",
    category: "utility",
  },
  {
    id: "random-box",
    name: "랜덤 박스",
    desc: "무작위 아이템이 들어있는 상자",
    price: 2200,
    emoji: "🎁",
    emojiColor: "bg-red-900/40",
    badge: "NEW",
    category: "item",
  },
  {
    id: "magic-intro",
    name: "마공학 입문 패키지",
    desc: "마공학 시작에 필요한 기본 구성",
    price: 6600,
    emoji: "⚗️",
    emojiColor: "bg-purple-900/40",
    category: "magic",
  },
  {
    id: "auto-mine-7",
    name: "자동 광질기 [7일]",
    desc: "7일 동안 자동 채굴 기능 활성화",
    price: 4400,
    emoji: "⛏️",
    emojiColor: "bg-stone-700/40",
    category: "utility",
  },
  {
    id: "storage-expand",
    name: "보관함 확장권",
    desc: "개인 보관함 슬롯 9칸 추가",
    price: 3300,
    emoji: "📦",
    emojiColor: "bg-amber-800/40",
    category: "utility",
  },
  {
    id: "pet-summon",
    name: "펫 소환권",
    desc: "무작위 희귀 펫 1마리 소환",
    price: 2750,
    emoji: "🐾",
    emojiColor: "bg-pink-900/40",
    category: "cosmetic",
  },
  {
    id: "jump-7",
    name: "점프 부스터 [7일]",
    desc: "7일 동안 점프력 강화",
    price: 3300,
    emoji: "🦘",
    emojiColor: "bg-green-900/30",
    category: "utility",
  },
  {
    id: "speed-7",
    name: "이동 속도 부스터 [7일]",
    desc: "7일 동안 이동 속도 증가",
    price: 3300,
    emoji: "💨",
    emojiColor: "bg-sky-900/40",
    category: "utility",
  },
];
